<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-O81F81N" failures="1" tests="13" name="Default test" time="118.113" errors="0" timestamp="2025-08-20T23:11:12 GMT-07:00">
  <testcase classname="testCases.testCases_Login" name="loginLogoTextDisplay" time="1.9"/>
  <testcase classname="testCases.testCases_Login" name="blankData" time="6.309"/>
  <testcase classname="testCases.testCases_Login" name="blankData" time="6.993"/>
  <testcase classname="testCases.testCases_Login" name="blankData" time="7.048"/>
  <testcase classname="testCases.testCases_Login" name="blankData" time="6.963"/>
  <testcase classname="testCases.testCases_Login" name="invalidEmailId" time="8.143"/>
  <testcase classname="testCases.testCases_Login" name="invalidEmailId" time="7.859"/>
  <testcase classname="testCases.testCases_Login" name="invalidEmailId" time="8.879"/>
  <testcase classname="testCases.testCases_Login" name="validationLogin" time="11.713"/>
  <testcase classname="testCases.testCases_Login" name="validationLogin" time="11.235"/>
  <testcase classname="testCases.testCases_Login" name="validationLogin" time="11.329"/>
  <testcase classname="testCases.testCases_Login" name="otherText" time="7.36"/>
  <testcase classname="testCases.testCases_Login" name="validLogin" time="15.589">
    <failure type="java.lang.AssertionError" message="expected [Please wait... while we are set up the Database] but found [Please wait... while we set up the Database]">
      <![CDATA[java.lang.AssertionError: expected [Please wait... while we are set up the Database] but found [Please wait... while we set up the Database]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.testCases_Login.validLogin(testCases_Login.java:137)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validLogin -->
</testsuite> <!-- Default test -->
